# Generated by Django 5.2.4 on 2025-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.IntegerField(verbose_name='Número da Sala')),
                ('capacity_room', models.IntegerField(verbose_name='Capacidade de Alunos')),
            ],
        ),
    ]
