# Generated by Django 5.2.4 on 2026-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/academico/sala/', verbose_name='Imagem da Sala'),
        ),
    ]
