# Generated by Django 5.2.4 on 2026-03-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_sala_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='codigo_seguranca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CÓDIGO DE SEGURANÇA'),
        ),
        migrations.CreateModel(
            name='HistoricoTurmaAluno',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ano_letivo', models.CharField(default='2024', max_length=9, verbose_name='Ano Letivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_turmas', to='apis.aluno', verbose_name='Aluno')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classe', verbose_name='Classe')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Histórico de Turma do Aluno',
                'verbose_name_plural': 'Históricos de Turmas dos Alunos',
                'db_table': 'historico_turma_aluno',
                'ordering': ['-data_inicio'],
                'indexes': [models.Index(fields=['id_aluno'], name='historico_t_id_alun_e21796_idx'), models.Index(fields=['id_aluno', 'ativo'], name='historico_t_id_alun_b22d17_idx'), models.Index(fields=['id_classe'], name='historico_t_id_clas_fd1a24_idx')],
            },
        ),
    ]
