# Generated by Django 5.2.4 on 2026-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_documento_codigo_seguranca_historicoturmaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='encarregado',
            name='modo_user',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo', max_length=20, verbose_name='Modo Usuário'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='modo_user',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo', max_length=20, verbose_name='Modo Usuário'),
        ),
    ]
