# Generated by Django 5.2.4 on 2026-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_encarregado_modo_user_alter_aluno_modo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_director',
            field=models.ImageField(blank=True, null=True, upload_to='config/assinaturas/', verbose_name='Assinatura do Director'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='carimbo_instituicao',
            field=models.ImageField(blank=True, null=True, upload_to='config/carimbos/', verbose_name='Carimbo da Instituição'),
        ),
        migrations.AlterField(
            model_name='solicitacaodocumento',
            name='status_solicitacao',
            field=models.CharField(choices=[('pendente', 'Aguardando Pagamento'), ('disponivel', 'Disponível'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=30, verbose_name='Status'),
        ),
    ]
