# Generated by Django 5.2.4 on 2026-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_add_assinatura_carimbo_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='sigla',
            field=models.CharField(max_length=10, null=True, verbose_name='Sigla da Disciplina'),
        ),
    ]
