# Generated by Django 5.2.4 on 2026-01-25 20:36

import apis.models.academico
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_fix_field_types'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='curso',
        #     name='duracao_meses',
        # ),
        migrations.RemoveField(
            model_name='documento',
            name='imagem_carimbo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_emissao_bilhete',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do Bilhete'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='provincia_naturalidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província de Naturalidade'),
        ),
        # migrations.AddField(
        #     model_name='curso',
        #     name='duracao',
        #     field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Duração (Anos)'),
        # ),
        # migrations.AddField(
        #     model_name='livro',
        #     name='recomendado',
        #     field=models.BooleanField(default=False, verbose_name='Recomendado'),
        # ),
        migrations.AddField(
            model_name='solicitacaodocumento',
            name='classe_solicitada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.classe', verbose_name='Classe Solicitada'),
        ),
        migrations.AddField(
            model_name='solicitacaodocumento',
            name='rupe',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='RUPE/Referência'),
        ),
        migrations.AddField(
            model_name='solicitacaodocumento',
            name='valor_rupe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do RUP'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/alunos/', verbose_name='Foto do Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Número do BI'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='senha_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_aluno',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Expulso', 'Expulso'), ('Transferido', 'Transferido'), ('Suspenso', 'Suspenso')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='caminho_pdf',
            field=models.FileField(null=True, upload_to='documentos/documents/pdfs/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('DECLARAÇÃO', 'DECLARAÇÃO'), ('BOLETIM', 'BOLETIM'), ('CERTIFICADO', 'CERTIFICADO')], max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='uuid_documento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='CÓDIGO ÚNICO DO DOCUMENTO'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/encarregados/images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='image/funcionario/images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dados_anteriores',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Dados Anteriores'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='dados_novos',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Dados Novos'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id_aluno',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='tipo_accao',
            field=models.CharField(editable=False, max_length=50, verbose_name='Tipo de Ação'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='dispositivo',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='hora_saida',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Hora de Saída'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_aluno',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_encarregado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.encarregado', verbose_name='Encarregado'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='ip_usuario',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='navegador',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, verbose_name='Navegador'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='caminho_arquivo',
            field=models.FileField(upload_to='documentos/library/books/', verbose_name='Arquivo em PDF'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='img_path',
            field=models.ImageField(upload_to='image/academico/sala/', verbose_name='Imagem da Sala'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.CharField(blank=True, default=apis.models.academico.current_year, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo_turma',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código da Turma'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado')], max_length=20, verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina')),
                ('id_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.funcionario', verbose_name='Professor')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='apis.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'db_table': 'horario',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
