# Generated by Django 5.2.4 on 2026-01-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_curso_duracao_meses_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='curso',
        #     name='duracao_meses',
        # ),
        # migrations.AddField(
        #     model_name='curso',
        #     name='duracao',
        #     field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Duração (Anos)'),
        # ),
        # migrations.AddField(
        #     model_name='livro',
        #     name='recomendado',
        #     field=models.BooleanField(default=False, verbose_name='Recomendado'),
        # ),
        migrations.CreateModel(
            name='MatrizCurricular',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_matriz_curricular', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição (ex: Grade 2024)')),
                ('ano_letivo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano Letivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classe', verbose_name='Classe')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Matriz Curricular',
                'verbose_name_plural': 'Matrizes Curriculares',
                'db_table': 'matriz_curricular',
                'unique_together': {('id_curso', 'id_classe', 'ano_letivo')},
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='id_matriz_curricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.matrizcurricular', verbose_name='Matriz Curricular'),
        ),
        migrations.CreateModel(
            name='MatrizCurricularDisciplina',
            fields=[
                ('id_matriz_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('carga_horaria', models.IntegerField(default=0, verbose_name='Carga Horária Semanal')),
                ('coeficiente', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coeficiente/Peso')),
                ('e_nuclear', models.BooleanField(default=True, verbose_name='É Nuclear?')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina')),
                ('id_matriz_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='apis.matrizcurricular', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Disciplina da Matriz',
                'verbose_name_plural': 'Disciplinas da Matriz',
                'db_table': 'matriz_curricular_disciplina',
                'unique_together': {('id_matriz_curricular', 'id_disciplina')},
            },
        ),
    ]
