# Generated by Django 5.2.4 on 2026-01-25 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_remove_curso_duracao_meses_curso_duracao_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='curso',
        #     name='duracao_meses',
        # ),
        # migrations.AddField(
        #     model_name='curso',
        #     name='duracao',
        #     field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Duração (Anos)'),
        # ),
        # migrations.AddField(
        #     model_name='livro',
        #     name='recomendado',
        #     field=models.BooleanField(default=False, verbose_name='Recomendado'),
        # ),
        migrations.AddField(
            model_name='nota',
            name='id_matriz_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.matrizcurriculardisciplina', verbose_name='Disciplina da Matriz'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='id_disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.disciplina', verbose_name='Disciplina'),
        ),
    ]
