# Generated by Django 5.2.4 on 2026-01-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_curso_duracao_meses_curso_duracao_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='curso',
        #     name='duracao_meses',
        # ),
        # migrations.AddField(
        #     model_name='curso',
        #     name='duracao',
        #     field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Duração (Anos)'),
        # ),
        # migrations.AddField(
        #     model_name='livro',
        #     name='recomendado',
        #     field=models.BooleanField(default=False, verbose_name='Recomendado'),
        # ),
        migrations.AddField(
            model_name='nota',
            name='tipo_nota',
            field=models.CharField(blank=True, choices=[('MAC', 'Média de Avaliação Contínua'), ('PP', 'Prova do Professor'), ('PT', 'Prova Trimestral')], max_length=20, null=True, verbose_name='Tipo de Nota'),
        ),
        migrations.AddField(
            model_name='nota',
            name='trimestre',
            field=models.CharField(blank=True, choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], max_length=10, null=True, verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo_avaliacao',
            field=models.CharField(blank=True, choices=[('Prova do Professor', 'Prova do Professor'), ('Prova Trimestral', 'Prova Trimestral'), ('Avaliação Continua', 'Avaliação Contínua')], max_length=30, null=True, verbose_name='Tipo de Avaliação'),
        ),
    ]
